### ISSUE TITLE
Refactor prototype REPL for SSH / login access

### ISSUE THREAD

**Issue by oubiwann** [hexagram30/mush#11]
Tasks:
* [ ] Support ssh'ing into game shell
* [ ] Run each shell in its own LFE process with its own state
* [ ] Set user data in that shell process' state
* [ ] Maybe perform various user look-ups as part of login (e.g., cache role-based data) so that DB queries may be avoided if possible -- store these in the login state, too
* [ ] Add readline support
* [ ] Enable only one instance of a single character logging in at a time
* [ ] Ensure multiple logins with different users work as expected

Probably best to finish the TCP registration server first ... (see #3)
