### ISSUE TITLE
Implement hxgm30 game / story data format

### ISSUE THREAD

**Issue by oubiwann** [hexagram30/mush#19]
Phase 1:

* [x] Design v1 for the game data format - #20
* [x] Create story repo - https://github.com/cnbb-games/undirvithr
* [x] Copy data to story repo - https://github.com/cnbb-games/undirvithr/issues/5
   * [x] From existing DB inserts (in migration files) to `.md` files in story repo
   * [x] Files should be navigable in Github via Markdown links
* [x] Delete inserted data from migration files

Phase 2:

* [x] Add game data to the MUSH (e.g., via `git subtree`) - #47
* ~Find a good Markdown parser (reader and writer) for Erlang that also supports Markdown metadata headers~
* [x] Repurpose the `hxgm30.story` repo for parsing story files, etc.
* [x] Create functions for `.adoc` data -> Erlang data structures
* [x] Create a generic data structure from parsed documents that can be used in the game

Background:
* See [Figure out long-term data plan](https://github.com/hexagram30/mush/issues/16)

**Comment by oubiwann** [comment]
Done.
