### ISSUE TITLE
Create registration / new user shell 

### ISSUE THREAD

**Issue by oubiwann** [hexagram30/mush#3]
Tasks:
* [x] support telnet access
* [x] identify all required commands
* [x] create help file for all commands
* [x] receive and store data in the session:
   * [x] session id
   * [x] email address
   * [x] ssh public key
   * [x] confirmation status
* [x] ensure that all commands that can work with session data do so correctly
* [x] update `service_user` schema (add new/missing fields)
* [x] extract DB errors and selectively display to users (e.g., if email address is already taken) - #21 
* [x] verify user accounts - #22
* [x] store all session data in the DB - #23
* [x] Keep user account table clean - #24

Blocks: #11

**Comment by oubiwann** [comment]
Current prototype needs to be refactored along the lines outlined by Fred in LYSE.

**Comment by oubiwann** [comment]
I'm going to put the registration supervisor under the top-level mush supervisor.

**Comment by oubiwann** [comment]
Here's something that could be used for TTL'ing unconfirmed users after 24 hours:
* https://stackoverflow.com/a/26063344

**Comment by oubiwann** [comment]
Sub-tasks and tickets are complete!
