### ISSUE TITLE
Add support for streaming event data for DB changes

### ISSUE THREAD

**Issue by oubiwann** [hexagram30/mush#39]
This can be done via Logical Decoding Output plugins in Postgres and some WAL/replication configuration setup.

Tasks:
* [ ] Explore the basic features and possibilities
* [ ] Install `wal2json` and experiment with it (see #41)
* [ ] Install `epgl` and experiment with it (see #41)
* [ ] Decide upon a plugin
* [ ] Create a new server in the mush supervision tree that manages event data (see #42)
