### ISSUE TITLE
Integrate hxgm30 game / story data format with MUSH DB 

### ISSUE THREAD

**Issue by oubiwann** [hexagram30/mush#46]
A continuation of the work in #19 

Phase 3:

* [ ] Create a conversion for `.adoc` to SQL - #44
* [ ] Create game content loaders in `hxgm30.game`
* [ ] Update `hxgm30.mush.app` to load game data before any networked services are started up

Phase 4: 

* [ ] Create game content `.adoc` writers in `hxgm30.game` (for preserving in-game edits in the file-based source of truth) - #45

Background:
* See [Figure out long-term data plan](https://github.com/hexagram30/mush/issues/16)
